### ISSUE TITLE
[Meta] Script Recorder GA requirements

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#250]
### Task summary

This issue defines the necessary remaining milestones before we're able to start labeling the recorder as a beta product:

- #### Release / Signing
    - [x] Code signing for macOS https://github.com/elastic/synthetics-recorder/pull/238
    - [x] Code signing for windows https://github.com/elastic/synthetics-recorder/issues/117
      - [x] Windows signing https://github.com/elastic/observability-robots/issues/1218
    - [x] Code signing for Linux https://github.com/elastic/synthetics-recorder/pull/238
    - [x] Binary notarization for macOS https://github.com/elastic/synthetics-recorder/issues/51
    - [x] Shipping `arm64`-compatible binary https://github.com/elastic/synthetics-recorder/issues/248
    - Recorder download from Elastic domain https://github.com/elastic/uptime/issues/461
      - We have a plan b for the download location to be https://github.com/elastic/synthetics-recorder/blob/main/docs/DOWNLOAD.md until a _proper_ location is set up later by PMM
    - [x] Remove beta labels https://github.com/elastic/synthetics-dev/issues/182
    - [x] Update Synthetics/PW https://github.com/elastic/synthetics-recorder/issues/393
    - [x] Release 1.0 (non beta) https://github.com/elastic/synthetics-dev/issues/183
- #### Documentation
    - [x] Document recorder: https://github.com/elastic/observability-docs/issues/1907
- #### Enhancement / Testing
    - [x] Delete actions while recording https://github.com/elastic/synthetics-recorder/issues/242
    - [x] #254
    - [x] #265 
    - [x] #262
    - [x] #263
    - [x] Add more E2E tests: https://github.com/elastic/synthetics-recorder/issues/113
    - [x] #264
    - [x] #277

### Post-GA features

- Onboarding UI https://github.com/elastic/synthetics-recorder/issues/74
- Mini window: https://github.com/elastic/synthetics-recorder/issues/88
- Kibana/service interaction
- Device type
- Fork/eject create react app (required for mini window) https://github.com/elastic/synthetics-recorder/issues/190

**Comment by justinkambic** [comment]
I have updated the Windows signing item to completed. AFAIK we are now signing windows binaries and there is no warning when trying to run them. @kyungeunni are you able to confirm?
