### ISSUE TITLE
Migrate Elastic Playwright fork to later version of official Playwright

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#262]
The version of Playwright we reference today is very out of date. Before we can make the Recorder GA, we are going to need to update Elastic's Playwright fork to the latest version referenced by Synthetics. Once we do this, we unblock ourselves from upgrading Playwright, Elastic Synthetics, etc.

This is important from a feature perspective, as well as a security standpoint. We can't make the Recorder GA until we're able to respond to emergency patches to all of its dependencies, including Synthetics/Playwright. Without accomplishing this upgrade, we will not be able to quickly patch our software in the event of a serious security issue, and thus we're not a candidate for production use until we have that capability.

## TODO

- [x] Update `@elastic/playwright` to latest upstream:main, or fresh fork the repo
- [x] Apply the patch we have in `separate-recorder` branch
- [x] Use latest `@elastic/synthetics` in recorder
