### ISSUE TITLE
Design spec changes for phase 1

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics-recorder#6]
https://whimsical.com/monitor-settings-and-management-NaWtQeMKvyHzzQYu5ex6Vr

## Tasks
+ [x] Assertion flow  - elastic/synthetics-recorder#7
+ [x] Show script logic - elastic/synthetics-recorder#8
+ [ ] Test result reporter enhancements
+ [x] Editable step names - elastic/synthetics-recorder#21 
+ [x] Assertion action changes - elastic/synthetics-recorder#22
