### ISSUE TITLE
[Script Recorder] Add clear all steps functionality with warning modal

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#70]
This is a subtask of https://github.com/elastic/synthetics-recorder/issues/54.

**User story:**
As a user, when creating a script that I'm not happy with, I want a way to start over.

**Proposed solution:** 
Add a button that allows users to remove all the steps they've previously recorded.

This button should trigger a confirmation dialogue as it's permanently destructive.

@liciavale if you have any design input on where this button should live and how it should look a comment with some lofi visualization would be enough to go on.

EDIT:

The scope of this issue has grown considerably. I'm adding this meta list of tasks that can be broken into sub-issues before we can close this.

- [ ] Add `delete all steps` button to enable user to clear previous actions and start again
  - include modal warning
- [ ] Update pause/stop/close/start-over functionality
- [ ] Implement dedicated "start" screen
- [ ] Implement updated step flow UI

It's likely there's overlap here with existing issues, we have just had numerous discussions on this thread and I wanted to summarize in the description.

**Comment by justinkambic** [comment]
I'm going to close this for now as we do have the functionality in the title implemented.

We still want to add a dedicated start screen - we should work on a dedicated ticket to add this, and move as much design work as can be reused for this purpose to that new home. The UI has changed quite a bit since this ticket was created, so we will want to reassess and make a fresh run at this.
