### ISSUE TITLE
Script recorder 8.1

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#87]
Meta issue to track requirements for each flow below:

**Doc**
- [Design doc](https://docs.google.com/document/d/1iYtVlbUTy4FV_-JKnJS-hrHOuG_iS7FuXHsQ3gZyF6E/edit#heading=h.5zlprzs7qjya)

**Design enanchment**
- [x] [Update header to match new design](https://github.com/elastic/synthetics-recorder/issues/106)

**Action**
- [x] [Edit an action recorded by the recorder](https://github.com/elastic/synthetics-recorder/issues/132)

**Assertion**
- [x] [Add a new assertion](https://github.com/elastic/synthetics-recorder/issues/65)
- [x] [Edit an assertion](https://github.com/elastic/synthetics-recorder/issues/65)
- [x] [Delete an assertion](https://github.com/elastic/synthetics-recorder/issues/65)

**Steps divider**
- [x]  [Add a new step divider](https://github.com/elastic/synthetics-recorder/issues/64)
- [x]  [Rename a step divider](https://github.com/elastic/synthetics-recorder/issues/64)
- [x]  [Collapse a step divider](https://github.com/elastic/synthetics-recorder/issues/64)
- [x]  [Delete a step divider](https://github.com/elastic/synthetics-recorder/issues/64)
- [x]  [Drag and drop a step divider](https://github.com/elastic/synthetics-recorder/issues/64) 

**Replay/test** 
- [x] [Replay/Test steps flow](https://github.com/elastic/synthetics-recorder/issues/131)

**Export script** 
- [x] [Export scripts allowing to select between inline/suite script](https://github.com/elastic/synthetics-recorder/issues/121)

**Copy and content**  
- [ ] Make sure we check the copy and we keep the content consistent

**Comment by liciavale** [comment]
New designs are here 
https://www.figma.com/file/6xfG7uIpgc84d62JnXhOMV/Script-recorder?node-id=10%3A45816
I'll try to finalise it asap with the flows that are missing

**Comment by lucasfcosta** [comment]
Btw, as a more general note, I'd suggest that we break this down into multiple issues for each part of the designs so that we can more easily keep track of it. What does everyone think?

**Comment by lucasfcosta** [comment]
@paulb-elastic during our 1:1 last week we have discussed making a gap analysis between the designs and what we have in this issue so that we could add more issues for 8.1 if necessary.

Here's the result of my gap analysis:

> Items with a ⭐  indicate I believe we need a new issue for them.

* **Step layout**: As you can see below, the steps in the recorder and the steps on the designs are different, however, I assume that will be addressed as part of the step separators, not just updating the step layout and then adding configurable separators. Therefore, I assume that's fine and we don't need another issue for it.
    <img width="613" alt="Screenshot 2021-12-20 at 09 39 56" src="https://user-images.githubusercontent.com/6868147/146746222-2a5715df-3a12-4600-a106-28b0de84c9ce.png">
    ![Screenshot 2021-12-20 at 09 39 52](https://user-images.githubusercontent.com/6868147/146746224-26c18c88-5e4e-4547-967b-a6ab8721125e.png)
*  ⭐  **Test results**: The new test results have a very different appearance from what is currently in the recorder. Currently, they're embedded into the main view. On the designs, they appear on a fly-out. Furthermore, the fly-out contents themselves are also very different. **I think we need a separate issue for this**.
    ![Screenshot 2021-12-20 at 09 41 31](https://user-images.githubusercontent.com/6868147/146746538-b2fd2811-6dc2-40e8-bbfd-06c5d2d052c4.png)
    <img width="1451" alt="Screenshot 2021-12-20 at 09 41 37" src="https://user-images.githubusercontent.com/6868147/146746530-53484ad3-1e27-4042-9285-c7f238768be6.png">
* ⭐  **Expanding replay steps**: In addition to the different layout for test replay results, users can also expand steps on the recorder. Expanding replayed steps is not _currently_ possible. **I think we need a separate issue for this**.
    <img width="540" alt="Screenshot 2021-12-20 at 09 46 40" src="https://user-images.githubusercontent.com/6868147/146747050-f43f651b-015a-461c-992d-690a82b0f716.png">
    ![Screenshot 2021-12-20 at 09 43 48](https://user-images.githubusercontent.com/6868147/146747054-a4236633-3c84-457d-b9d1-5ab342ebf11e.png)
* **Editing actions**: Editing actions is currently significantly different. However, given we'll do lots of changes to add step separators, I believe we can bundle the new edit layout in them.
    ![Screenshot 2021-12-20 at 09 47 42](https://user-images.githubusercontent.com/6868147/146747320-8eb418ad-6b71-4b8b-9a41-e3c90f63ce3a.png)
    <img width="592" alt="Screenshot 2021-12-20 at 09 47 50" src="https://user-images.githubusercontent.com/6868147/146747316-545ef145-eb8f-42e9-b544-88e3e504030a.png">
 * ⭐  **Exporting scripts**: Currently, exporting scripts opens a dialog to save the journey's code. On the designs, on the other hand, the journey's code appears within a fly-out from which the user can copy the code. **I think we need a separate issue for this**.
    ![Screenshot 2021-12-20 at 09 49 32](https://user-images.githubusercontent.com/6868147/146747692-29e33d1f-9810-4044-bda4-cc15bf0598b5.png)
    <img width="1444" alt="Screenshot 2021-12-20 at 09 51 17" src="https://user-images.githubusercontent.com/6868147/146747771-c493cab1-154e-479b-9bd1-7440d7235b0f.png">

**Comment by paulb-elastic** [comment]
Thanks for going through this @lucasfcosta.  I agree, it seems those three differences should have separate issues, whereas the other points should be covered elsewhere.  @liciavale, do you happen to already have these three covered elsewhere, or ok for Lucas to create them?

**Comment by paulb-elastic** [comment]
> ...do you happen to already have these three covered elsewhere, or ok for Lucas to create them?

@liciavale for example, https://github.com/elastic/synthetics-recorder/issues/121

**Comment by liciavale** [comment]
@paulb-elastic @lucasfcosta we have some issues, but some that @lucasfcosta mentioned are missing. I'll create them and link them to this meta

**Comment by paulb-elastic** [comment]
@liciavale can we close this now (with other issues tracking further specific updates)?

**Comment by liciavale** [comment]
Hey @paulb-elastic I'd like to cover the last point about copy and content before closing it.

**Comment by liciavale** [comment]
Yes, we should do it when the last PRs are merged in, I can do it but it also depends on the conversation regarding suites/inline, etc.
 I wanted to track it somewhere, I'm ok if we close the issue, I think we should just have this somewhere tho'.

**Comment by justinkambic** [comment]
We haven't merged implementations for all of the items described in this issue. I think this issue is more from a design perspective, but if we want to wait until all the work is done for these then the issue should stay open.

**Comment by paulb-elastic** [comment]
Moving onto the 8.2 board

**Comment by kyungeunni** [comment]
Hello @liciavale, I just wanted to clarify this task in the first comment:
 
>Make sure we check the copy and we keep the content consistent

Does it refer to a functionality copying script content to the clipboard in the Export flyout and making sure the content is as same as the one shown in the flyout preview?
![image](https://user-images.githubusercontent.com/16660866/164190464-f968c42b-f7e9-4adf-841e-e00c04e99074.png)
